name: Flask Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code repository checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build -t abdulrmohammed/flask-docker:latest .
      
    - name: Push the Docker image
      run: docker push abdulrmohammed/flask-docker:latest
